name: CI
on:
  push:
    tags:
      - v*

jobs:
  tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          version: ${{ steps.extract_version.outputs.VERSION }}
          release: true
          body: |
            ## Installation

            ### macOS

            ```bash
            brew install jaywcjlove/tap/spa
            brew reinstall jaywcjlove/tap/spa
            ```